Implemented more detailed and precise activity time measuring
wakatime/visualstudio-wakatime pull request #107
Opened 2020-09-01 21:04 UTC by MattLebrao

Enhancements proposed on wakatime/visualstudio-wakatime#106

### Note on .csproj reference:
I had to remove the original reference so the signed extension utils dll and replace with a reference to my locally built file. I will obviously not gonna commit the .csproj file with the reference change, which means this code **will only run** with the original reference once the pull request wakatime/nuget-wakatime-shared-extension-utils#3 has been merged and the binary rebuilt.

# The IDE Events

The plugin can now respond to new IDE events:
- Debugging [`DebuggerEvents`]
    - `OnEnterRunMode`
    - `OnEnterBreakMode`
    - `OnEnterDesignMode`
- Building [`BuildEvents`]
    - `OnBuildProjConfigBegin`
    - `OnBuildProjConfigDone`
- Coding [`TextEditorEvents`]
    - `LineChanged`

Previously Implemented and updated:
- Coding
    - [`DocumentEvents`]
        - `DocumentOpened`
        - `DocumentSaved`
    - [`WindowEvents`]
        - `WindowActivated`

Events not issuing heartbeats:
- [`SolutionEvents`]
    - `Opened`

## Heartbeat and Event Categories

The event's holding class categorizes the event type, and therefore the heartbeat category is closely related to it:

- DebuggerEvents:
    - All events issued are related to the debug flow, and are **NOT** triggered by file changes.
    - These events will issue heartbeat indicating the _debugging_ activity, with the actual debugging project's output file full name. 
    - File change related events will monitor the debugger mode to change the file action accordingly.
- BuildEvents:
    - These events are raised when build begins and ends only.
    - File changed events will monitor if an ongoing build exists so they can continue to issue heartbeats for the project's "building" activity.
- DocumentEvents & TextEditorEvents
    - These events are used to detect changes made to the files.
    - The `LineChanged` event will bring the plugin in accordance to the guidelines on [Creating a Plugin: Handling Editor Events](https://wakatime.com/help/creating-plugin#handling-editor-events)

## Heartbeat Setups

Below we will go over how each event will setup a heartbeat through the `WakaTime.HandleActivity` method:

> **Remark**
> The "Project" parameter is common to all events: `GetProjectName()`.

### The new events:

- Debugging [`DebuggerEvents`]
    - `OnEnterRunMode`
        - Entity: (ProjectOutput) (the solution's current start-up project) [1]
        - IsWrite: False
        - Category: "debugging"
        - EntityType: "file"
    - `OnEnterBreakMode`
        - Entity: (ProjectOutput) (the solution's current start-up project) [1]
        - IsWrite: False
        - Category: "debugging"
        - EntityType: "file"
    - `OnEnterDesignMode`
        - Entity: (ProjectOutput)  (the solution's current start-up project) [1]
        - IsWrite: False
        - Category: "debugging"
        - EntityType: "file"
- Building [`BuildEvents`]
    - `OnBuildProjConfigBegin`
        - Entity: (ProjectOutput)  (as supplied by event argument) [2]
        - IsWrite: False
        - Category: "building"
        - EntityType: "file"
    - `OnBuildProjConfigDone`
        - Entity: (ProjectOutput)  (as supplied by event argument) [2]
        - IsWrite: True/False  (according to the `Success` event argument) [3]
        - Category: "building"
        - EntityType: "file"
- Coding [`TextEditorEvents`]
    - `LineChanged`
        - Heartbeat 1
            - Entity: (ChangedDocument) (as supplied by event argument) [2]
            - IsWrite: False
            - Category:
                - Debugger in Break mode: "debugging"
                - Debugger in Run or Design mode: "coding"
            - EntityType: "file"
        - Heartbeat 2 (if a build is in progress)
            - Entity: (ProjectOutput) (for currently building project, not the currently focused one) [4]
            - IsWrite: False
            - Category: "building"
            - EntityType: "file"

### Previously implemented updated events:

- Coding
    - [`DocumentEvents`]
        - `DocumentOpened`
            - Heartbeat 1
                - Entity: (OpenedDocument) (as suplied by event argument) [2]
                - IsWrite: False
                - Category:
                    - Debugger in Break mode: "debugging"
                    - Debugger in Run or Design mode: "coding"
                - EntityType: "file"
            - Heartbeat 2 (if a build is in progress)
                - Entity: (ProjectOutput) (for currently building project, not the currently focused one) [4]
                - IsWrite: False
                - Category: "building"
                - EntityType: "file"
        - `DocumentSaved`
            - Heartbeat 1
                - Entity: (SavedDocument) (as supplied by event argument) [2]
                - IsWrite: True
                - Category:
                    - Debugger in Break mode: "debugging"
                    - Debugger in Run or Design mode: "coding"
                - EntityType: "file"
            - Heartbeat 2 (if a build is in progress)
                - Entity: (ProjectOutput) (for currently building project, not the currently focused one) [4]
                - IsWrite: False
                - Category: "building"
                - EntityType: "file"
    - [`WindowEvents`]
        - `WindowActivated`
            - Heartbeat 1
                - Entity: (ActivatedWindowDocument) (as supplied by event argument) [2]
                - IsWrite: False
                - Category:
                    - Debugger in Break mode: "debugging"
                    - Debugger in Run or Design mode: "coding"
                - EntityType: "file"
            - Heartbeat 2 (if a build is in progress)
                - Entity: (ProjectOutput) (for currently building project, not the currently focused one) [4]
                - IsWrite: False
                - Category: "building"
                - EntityType: "file"

> **Notes**:
>**[1]** *(the solution's current start-up project)*: When the debugger begins, it locks the solution settings such that the start-up project can't be changed. This will always retrieve the actual project currently being debugged.
> **[2]** *(as supplied by event argument)*: Parameters that come from the events arguments ensure they will be correct in the unlikely event that the solution settings change between the invocation of the event and a possible attempt to get the current COM object (whether it's a Document, Project, etc).
> **[3]** *(according to the `Success` event argument)*: Only when the build is successful the project output file is actually written to, overwriting the previous successful build.
> **[4]** *(for currently building project, not the currently focused one)*: When the build begins, it stores the output file for the project supplied by the event, ensuring we won't mis-read the building project if the active project changes during an ongoing build.

2020-09-05 18:00 UTC, gandarez requested changes
In general we are handling all necessary events for the purpose of this PR. However there are quite few changes that I recommend to be changed. For the majority changes I left comments here but to not get too messy I created a branch with some changes and you can see the difference here https://github.com/wakatime/visualstudio-wakatime/commit/1a7f4c8de3bebf5cb6e4a759185e101d1276a7e6

2020-09-06 06:51 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +        private void DebuggerEventsOnEnterRunMode(dbgEventReason Reason)
That's the default parameter name inserted by VS upon add the event handler. I'll change it, but it isn't even used in the event.

2020-09-06 06:51 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +                var activity = ObjDte.Debugger.CurrentMode == dbgDebugMode.dbgBreakMode ? HeartbeatCategory.Debugging : HeartbeatCategory.Coding;
Misspelled how?

2020-09-06 07:02 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +            var project = (Project)((object[])ObjDte.ActiveSolutionProjects)[0];
I'll look into a safer way to run this method.
As far as I know `ActiveSolutionProjects` will always contain only `Project` items, however I just realized I don't know it that is still true for ASP.NET projects. I'll test that.
I also realized I do not know what would happen should this method get called in an empty solution.
(Although it shouldn't get called at all, since the build events shouldn't get called in an empty solution. I'll test whether VS still raises these events in case the user tries to build an empty solution.)

2020-09-06 07:10 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +            var project = ObjDte.Solution.Projects.Cast<Project>().Where(proj => proj.UniqueName == Project).FirstOrDefault();
Wow, hard to believe I never noticed `FirstOrDefault` had a predicate argument.

2020-09-06 07:16 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +            var config = project.ConfigurationManager.Cast<EnvDTE.Configuration>().Where(conf => conf.PlatformName == Platform && conf.ConfigurationName == ProjectConfig).FirstOrDefault();
Config will never be null, since the project and configuration names in this method come from the build event handlers, which will always point towards existing and consistent project/configuration profiles. This method is only ever called from those handlers.

2020-09-06 07:16 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +            var config = project.ConfigurationManager.Cast<EnvDTE.Configuration>().Where(conf => conf.PlatformName == Platform && conf.ConfigurationName == ProjectConfig).FirstOrDefault();
Expression simplified and line break added.

2020-09-06 07:22 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +                var fullOutputName = GetCurrentProjectOutputForCurrentConfiguration();
I can make that change if you think it's important, but I believe the name `currentFile` is mis-leading (speaking of code readability).
`currentFile` could lead one to think it refers to the currently focused file, which is not the case. This is the output file from the project's settings.
How about `outputFile`?

2020-09-06 07:22 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +                var fullOutputName = GetCurrentProjectOutputForCurrentConfiguration();
I can make that change if you think it's important, but I believe the name `currentFile` is mis-leading (speaking of code readability).
`currentFile` could lead one to think it refers to the currently focused file, which is not the case. This is the output file from the project's settings.
How about `outputFile`?

2020-09-06 07:23 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +                var fullOutputName = GetCurrentProjectOutputForCurrentConfiguration();
I can make that change if you think it's important, but I believe the name `currentFile` is mis-leading (speaking of code readability).
`currentFile` could lead one to think it refers to the currently focused file, which is not the case. This is the output file from the project's settings.
How about `outputFile`?

2020-09-06 07:25 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +        private void BuildEventsOnBuildProjConfigBegin(string Project, string ProjectConfig, string Platform, string SolutionConfig)
Same thing. Default names created by VS upon creating the handler. Changed anyway.

2020-09-06 07:26 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +                _runningBuildOutput = fullOutputName;
I can make that change if you think it's important, but I believe the name `currentFile` is mis-leading (speaking of code readability).
`currentFile` could lead one to think it refers to the currently focused file, which is not the case. This is the output file from the project's settings.
How about `outputFile`?

2020-09-06 07:27 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +                var fullOutputName = GetProjectOutputForConfiguration(Project, Platform, ProjectConfig);
I can make that change if you think it's important, but I believe the name `currentFile` is mis-leading (speaking of code readability).
`currentFile` could lead one to think it refers to the currently focused file, which is not the case. This is the output file from the project's settings.
How about `outputFile`?

2020-09-06 07:28 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +                WakaTime.HandleActivity(fullOutputName, false, GetProjectName(), HeartbeatCategory.Building); //eventType defaults to "file"
I can make that change if you think it's important, but I believe the name `currentFile` is mis-leading (speaking of code readability).
`currentFile` could lead one to think it refers to the currently focused file, which is not the case. This is the output file from the project's settings.
How about `outputFile`?

(comment removed)

2020-09-08 15:42 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                var activity = ObjDte.Debugger.CurrentMode == dbgDebugMode.dbgBreakMode ? HeartbeatCategory.Debugging : HeartbeatCategory.Coding;
It's a `category` not `activity`,  isn't it?

2020-09-08 15:44 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                var fullOutputName = GetCurrentProjectOutputForCurrentConfiguration();
let's use `outputFile` though

2020-09-08 15:44 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                var fullOutputName = GetCurrentProjectOutputForCurrentConfiguration();
let's use `outputFile` though

2020-09-08 15:44 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                var fullOutputName = GetCurrentProjectOutputForCurrentConfiguration();
let's use `outputFile` though

2020-09-08 15:45 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                _runningBuildOutput = fullOutputName;
let's use `outputFile` though

2020-09-08 15:46 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                var fullOutputName = GetProjectOutputForConfiguration(Project, Platform, ProjectConfig);
let's use `outputFile` though

2020-09-08 15:46 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                WakaTime.HandleActivity(fullOutputName, false, GetProjectName(), HeartbeatCategory.Building); //eventType defaults to "file"
let's use `outputFile` though

2020-09-08 16:41 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +                var activity = ObjDte.Debugger.CurrentMode == dbgDebugMode.dbgBreakMode ? HeartbeatCategory.Debugging : HeartbeatCategory.Coding;
Ah, misnamed then. They refer to the same thing. The CLI calls it "category", the UI calls it "activity". I'll change to category to maintain consistency (also with the enum name).

2020-09-08 18:29 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +            var project = (Project)((object[])ObjDte.ActiveSolutionProjects)[0];
I've done some tests. Different project types will affect the `GetProjectOutputForConfiguration` and `GetCurrentProjectOutputForCurrentConfiguration`. For instance, a website won't have an "output" property, and so will fail in both method.

I thought of just using a try/catch block and in case of an exception either fallback to `GetProjectName()` (not sure if using the project name as entity is a good idea) or returning an empty string. Which do you think it should do?

How does wakatime treats heartbeats with an empty entity value? Are they ignored?

2020-09-08 18:37 UTC, MattLebrao commented on WakaTime/WakaTimePackage.cs
> +            var project = (Project)((object[])ObjDte.ActiveSolutionProjects)[0];
The NuGet package will ignore a call to `HandleActivity` with a null entity value, but not with an empty one. Returning null on those methods would mean that for projects such as websites and _et al._ that might break the methods. This means that the plugin wouldn't record heartbeats by the build and debugger events, but it would still record coding activity as always has, and additionally will still record "debugging" activity for file changed events while the debugger is running.

2020-09-28 22:15 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                // setup event handlers
blank spaces at the end

2020-09-28 22:16 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                var outputFile = GetCurrentProjectOutputForCurrentConfiguration();
break line here

2020-09-28 22:18 UTC, gandarez requested changes
some comments left

2020-09-28 22:18 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                var outputFile = GetCurrentProjectOutputForCurrentConfiguration();
break line here

2020-09-28 22:18 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                var outputFile = GetCurrentProjectOutputForCurrentConfiguration();
break line here

2020-09-28 22:18 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                // setup event handlers
blank spaces at the end

2020-09-28 22:18 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                var outputFile = GetCurrentProjectOutputForCurrentConfiguration();
break line here

2020-09-28 22:18 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                _isBuildRunning = true;
break line here and for the other 3 lines

2020-09-28 22:18 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                _isBuildRunning = false;
break line here and for the other 2 lines

2020-09-28 22:18 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                if (document != null)
break line here

2020-09-28 22:18 UTC, gandarez commented on WakaTime/WakaTimePackage.cs
> +                var project = (Project)((object[])ObjDte.ActiveSolutionProjects)[0];
break line here

2020-10-01 15:39 UTC, merged